### ISSUE TITLE
AttributeError: 'CacheFile' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by eriophora** [menpo/landmarkerio-server#19]
Following the installation directions, I installed via:

`conda install -c menpo landmarkerio`

then, navigating to the image folder, 

`lmio image ./test_images`

which cases it to fail with a very large stack trace, the last error is:

```
...........................................................................
//anaconda/lib/python2.7/posixpath.pyc in join(a='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF/1691766_1.jpg', *p=(<CacheFile.image: 'image.json'>,))
     63     If any component is an absolute path, all previous path components
     64     will be discarded.  An empty last part will result in a path that
     65     ends with a separator."""
     66     path = a
     67     for b in p:
---> 68         if b.startswith('/'):
     69             path = b
     70         elif path == '' or path.endswith('/'):
     71             path +=  b
     72         else:

AttributeError: 'CacheFile' object has no attribute 'startswith'
```

OS is OS X Sierra. Conda is a fresh install (python 2.7.12).

**Comment by jabooth** [comment]
Can you give the full stack trace please?

**Comment by eriophora** [comment]
Certainly. Here it is:

```
assets:    /Users/eriophora/helen_testing/testims
cache:     /var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF
Using glob: "*"
5 assets need to be added to the cache
Traceback (most recent call last):
  File "//anaconda/bin/lmio", line 95, in <module>
    glob=ns.glob)
  File "//anaconda/bin/lmio", line 23, in main
    ext=ext, glob=glob)
  File "//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py", line 261, in cache_assets
    recursive=recursive, ext=ext, glob=glob)
  File "//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py", line 230, in build_cache
    cacher_f(cache, path_asset_id)
  File "//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py", line 189, in parallel_cacher
    for path, asset_id in path_asset_id)
  File "//anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 660, in __call__
    self.retrieve()
  File "//anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 543, in retrieve
    raise exception_type(report)
joblib.my_exceptions.JoblibAttributeError: JoblibAttributeError
___________________________________________________________________________
Multiprocessing exception:
    ...........................................................................
//anaconda/bin/lmio in <module>()
     90     ns = parser.parse_args()
     91     main(ns.mode, ns.path, recursive=ns.recursive, ext=ns.ext,
     92          template_dir=ns.templates, collection_dir=ns.collections,
     93          cache_dir=ns.cache, dev=ns.dev, port=port, public=ns.public,
     94          upgrade_templates=ns.upgrade_templates,
---> 95          glob=ns.glob)
     96 
     97 
     98 
     99 

...........................................................................
//anaconda/bin/lmio in main(mode='image', asset_dir='./testims', recursive=False, ext=None, template_dir=None, collection_dir=None, cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', dev=False, port=5000, public=False, upgrade_templates=False, glob=None)
     18     if cache_dir is None:
     19         cache_dir = tempfile.mkdtemp()
     20     identifier_f = filepath_as_asset_id_under_dir(asset_dir)
     21     _, asset_ids_to_path = cache_assets(mode, identifier_f, asset_dir,
     22                                         cache_dir, recursive=recursive,
---> 23                                         ext=ext, glob=glob)
        ext = None
        glob = None
     24     # build an inplace adapter to serve landmarks found in-situ next to assets
     25     lm_adapter = InplaceFileLmAdapter(asset_ids_to_path)
     26     app = serve_from_cache(mode, cache_dir, lm_adapter,
     27                            template_dir=template_dir,

...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py in cache_assets(mode='image', identifier_f=<function path_as_asset_id>, asset_dir='./testims', cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', recursive=False, ext=None, glob=None)
    256     elif mode == 'mesh':
    257         cache_builder = build_mesh_parallel_cache
    258     else:
    259         raise ValueError("mode must be 'image' or 'mesh'")
    260     return cache_builder(identifier_f, asset_dir, cache_dir,
--> 261                          recursive=recursive, ext=ext, glob=glob)
        recursive = False
        ext = None
        glob = None
    262 
    263 
    264 
    265 

...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py in build_cache(cacher_f=<function parallel_cacher>, asset_path_f=<functools.partial object>, cache_f=<function cache_image>, identifier_f=<function path_as_asset_id>, asset_dir='/Users/eriophora/helen_testing/testims', cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', recursive=False, ext=None, glob=None)
    225     print('{} assets need to be added to '
    226           'the cache'.format(len(uncached)))
    227     cache = partial(cache_asset, cache_dir, cache_f)
    228     path_asset_id = [(asset_id_to_paths[a_id], a_id) for a_id in uncached]
    229     start = time.time()
--> 230     cacher_f(cache, path_asset_id)
        cacher_f = <function parallel_cacher>
        cache = <functools.partial object>
        path_asset_id = [(PosixPath('/Users/eriophora/helen_testing/testims/1691766_1.jpg'), '1691766_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/1629243_1.jpg'), '1629243_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/232194_1.jpg'), '232194_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/10405146_1.jpg'), '10405146_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/2908549_1.jpg'), '2908549_1.jpg')]
    231     elapsed = time.time() - start
    232     if len(uncached) > 0:
    233         print('{} assets cached in {:.0f} seconds'.format(len(uncached),
    234                                                         elapsed))

...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.py in parallel_cacher(cache=<functools.partial object>, path_asset_id=[(PosixPath('/Users/eriophora/helen_testing/testims/1691766_1.jpg'), '1691766_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/1629243_1.jpg'), '1629243_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/232194_1.jpg'), '232194_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/10405146_1.jpg'), '10405146_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/2908549_1.jpg'), '2908549_1.jpg')], n_jobs=-1)
    184 
    185 
    186 def parallel_cacher(cache, path_asset_id, n_jobs=-1):
    187     from joblib import Parallel, delayed
    188     Parallel(n_jobs=n_jobs, verbose=5)(delayed(cache)(path, asset_id)
--> 189                                        for path, asset_id in path_asset_id)
        path_asset_id = [(PosixPath('/Users/eriophora/helen_testing/testims/1691766_1.jpg'), '1691766_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/1629243_1.jpg'), '1629243_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/232194_1.jpg'), '232194_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/10405146_1.jpg'), '10405146_1.jpg'), (PosixPath('/Users/eriophora/helen_testing/testims/2908549_1.jpg'), '2908549_1.jpg')]
    190 
    191 
    192 def build_cache(cacher_f, asset_path_f, cache_f, identifier_f, asset_dir,
    193                 cache_dir, recursive=False, ext=None, glob=None):

...........................................................................
//anaconda/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object <genexpr>>)
    655             if pre_dispatch == "all" or n_jobs == 1:
    656                 # The iterable was consumed all at once by the above for loop.
    657                 # No need to wait for async callbacks to trigger to
    658                 # consumption.
    659                 self._iterating = False
--> 660             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
    661             # Make sure that we get a last message telling us we are done
    662             elapsed_time = time.time() - self._start_time
    663             self._print('Done %3i out of %3i | elapsed: %s finished',
    664                         (len(self._output),

    ---------------------------------------------------------------------------
    Sub-process traceback:
    ---------------------------------------------------------------------------
    AttributeError                                     Thu Jan 12 13:42:41 2017
PID: 28918                             Python 2.7.12: //anaconda/bin/python
...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.pyc in cache_asset(cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', cache_f=<function cache_image>, path=PosixPath('/Users/eriophora/helen_testing/testims/1691766_1.jpg'), asset_id='1691766_1.jpg')
     83     The id of the asset that needs to be cached
     84     """
     85     asset_cache_dir = p.join(cache_dir, asset_id)
     86     if not p.isdir(asset_cache_dir):
     87         os.mkdir(asset_cache_dir)
---> 88     cache_f(cache_dir, path, asset_id)
     89 
     90 
     91 # IMAGE CACHING
     92 

...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.pyc in cache_image(cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', path=PosixPath('/Users/eriophora/helen_testing/testims/1691766_1.jpg'), asset_id='1691766_1.jpg')
     92 
     93 def cache_image(cache_dir, path, asset_id):
     94     r"""Actually cache this asset_id.
     95     """
     96     img = menpo.io.import_image(path)
---> 97     _cache_image_for_id(cache_dir, asset_id, img)
     98 
     99 
    100 def _cache_image_for_id(cache_dir, asset_id, img):
    101     asset_cache_dir = p.join(cache_dir, asset_id)

...........................................................................
//anaconda/lib/python2.7/site-packages/landmarkerio/cache.pyc in _cache_image_for_id(cache_dir='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF', asset_id='1691766_1.jpg', img=<menpo.image.base.Image object>)
     97     _cache_image_for_id(cache_dir, asset_id, img)
     98 
     99 
    100 def _cache_image_for_id(cache_dir, asset_id, img):
    101     asset_cache_dir = p.join(cache_dir, asset_id)
--> 102     image_info_path = p.join(asset_cache_dir, CacheFile.image)
    103     texture_path = p.join(asset_cache_dir, CacheFile.texture)
    104     thumbnail_path = p.join(asset_cache_dir, CacheFile.thumbnail)
    105     img_path = img.path
    106 

...........................................................................
//anaconda/lib/python2.7/posixpath.pyc in join(a='/var/folders/qr/1vty98092csdq2ps0plxjrx000ck10/T/tmpIKPyVF/1691766_1.jpg', *p=(<CacheFile.image: 'image.json'>,))
     63     If any component is an absolute path, all previous path components
     64     will be discarded.  An empty last part will result in a path that
     65     ends with a separator."""
     66     path = a
     67     for b in p:
---> 68         if b.startswith('/'):
     69             path = b
     70         elif path == '' or path.endswith('/'):
     71             path +=  b
     72         else:

AttributeError: 'CacheFile' object has no attribute 'startswith'
```

**Comment by csagonas** [comment]
I have the same at Ubuntu 16.04 with Conda 4.2.13, Python 2.7.11.

`/home/christos/anaconda2/envs/lmio/lib/python2.7/posixpath.pyc in join(a='/tmp/tmp97KCqT/289570.jpg', *p=(<CacheFile.image: 'image.json'>,))
     63     If any component is an absolute path, all previous path components
     64     will be discarded.  An empty last part will result in a path that
     65     ends with a separator."""
     66     path = a
     67     for b in p:
---> 68         if b.startswith('/'):
     69             path = b
     70         elif path == '' or path.endswith('/'):
     71             path +=  b
     72         else:
`

**Comment by jabooth** [comment]
Hmm this seems to be related to the version of `enum` being used.

@csagonas and @eriophora can you provide the output of
```
conda list
```
within the conda environment where you have `landmarkerio` installed?

**Comment by csagonas** [comment]
```
aniso8601                 0.82                     py27_0    menpo
apptools                  4.4.0                    py27_0    menpo
assimp                    3.0.1270                      0    menpo
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
boost                     1.56.0                   py27_3    menpo
bzip2                     1.0.6                         3  
cairo                     1.14.8                        0  
cherrypy                  3.8.0                    py27_0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
cyassimp                  0.2.2                    py27_0    menpo
cycler                    0.10.0                   py27_0  
cyffld2                   0.2.4                    py27_0    menpo
cypico                    0.2.7                    py27_0    menpo
cyrasterize               0.2.5                    py27_0    menpo
cyvlfeat                  0.4.5                    py27_0    menpo
decorator                 4.0.11                   py27_0  
dlib                      18.16                    py27_0    menpo
entrypoints               0.2.2                    py27_0  
enum                      0.4.4                    py27_0    menpo
enum34                    1.1.6                    py27_0  
envisage                  4.5.1                    py27_0    menpo
fftw                      3.3.4                         0    menpo
flask                     0.10.1                   py27_2  
flask-restful             0.2.12                   py27_0    menpo
fontconfig                2.12.1                        1  
freetype                  2.5.5                         2  
funcsigs                  0.4                      py27_0  
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
glew                      1.11.0                        0    menpo
glfw3                     3.0.4                         0    menpo
glib                      2.50.2                        1  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
ipykernel                 4.5.2                    py27_0  
ipython                   4.2.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.1.1                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jinja2                    2.9.4                    py27_0  
joblib                    0.8.4                    py27_0    menpo
jpeg                      8d                            2  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.1                    py27_0  
landmarkerio              0.4.0                    py27_0    menpo
libffi                    3.2.1                         1  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.4                         0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np110py27_0  
mayavi                    4.4.4                    py27_0    menpo
menpo                     0.6.2                    py27_0    menpo
menpo-pyvrml97            2.3.0a4                  py27_2    menpo
menpo3d                   0.3.0                    py27_0    menpo
menpodetect               0.3.0                    py27_0    menpo
menpofit                  0.3.1                    py27_0    menpo
menpoproject              1.0                        py_1    menpo
menpowidgets              0.1.2                    py27_0    menpo
mistune                   0.7.3                    py27_0  
mkl                       11.3.3                        0  
mock                      1.3.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.3.1                    py27_0  
numpy                     1.10.4                   py27_2  
openblas                  0.2.14                        4  
opencv                    2.4.11                 nppy27_0    menpo
openssl                   1.0.2j                        0  
pango                     1.40.3                        1  
path.py                   10.0                     py27_0  
pathlib                   1.0                      py27_1    menpo
pathlib2                  2.2.0                    py27_0  
pbr                       1.3.0                    py27_0  
pcre                      8.39                          1  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    3.0.0                    py27_1  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
prompt_toolkit            1.0.9                    py27_0  
ptyprocess                0.5.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pydispatcher              2.0.3                    py27_0    menpo
pyface                    5.1.0                    py27_0    menpo
pygments                  2.1.3                    py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_4  
python                    2.7.11                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2016.10                  py27_0  
pyyaml                    3.11                     py27_4  
pyzmq                     16.0.2                   py27_0  
qt                        4.8.7                         4  
qtconsole                 4.2.1                    py27_0  
readline                  6.2                           2  
scandir                   1.4                      py27_0  
scikit-learn              0.17.1              np110py27_2  
scipy                     0.16.0              np110py27_1  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
simpleparse               2.1.1                    py27_0    menpo
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_1  
system                    5.8                           2  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
traits                    4.5.0                    py27_0    menpo
traitsui                  5.1.0                    py27_0    menpo
vlfeat                    0.9.20                        1    menpo
vtk                       7.0.0                    py27_0    menpo
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.15                  py27_0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3
```

**Comment by jabooth** [comment]
Interesting, you have both `enum` and `enum34` - this is the problem.

Try
```
> conda remove --force enum34
```
And see if it works.

Note that this will break something somewhere else in menpo, as a different project (I'm not sure which @patricksnape ?) is depending on `enum34`. But it will at least get this working for you again for now.

**Comment by eriophora** [comment]
I also have both enum and enum34 installed, I'll try removing enum34. Thanks!

**Comment by patricksnape** [comment]
Hmmmmmm I wonder which dep needs enum34...

**Comment by patricksnape** [comment]
```
conda create --dry-run --json -n dummy -c menpo ipython | grep -i enum
      "enum34-1.1.6-py27_0 1", 
```

Looks like IPython (aka menpowidgets) is the culprit. Which is a serious issue. I think you need to change to using enum34 here @jabooth

**Comment by jabooth** [comment]
@patricksnape yup, fair enough. This will smooth over Py 2/3 support too (`enum34` is a true back port of the stdlib `enum` I believe.

**Comment by jabooth** [comment]
Landmarkerio v0.4.1 has just been released with a fix for this issue.
